-- =====================================================================
--  Almoxarifado · Categorias dos itens do estoque (planilha Livro2, com a coluna de categoria)
--  Cole TODO este arquivo no SQL Editor do Supabase e clique em "Run".
--
--  O que faz:
--    1. Cria a coluna "categories" nos itens (um item pode ter MAIS DE UMA categoria,
--       por exemplo "Acessório" e "Max Forte" ao mesmo tempo).
--    2. Preenche a categoria dos 308 itens da planilha (casando por nome + tamanho).
--
--  O que NÃO faz: não altera saldo, estoque mínimo, custo, postos nem o histórico.
--  Nenhuma entrada ou saída já registrada é tocada.
--
--  Pode rodar mais de uma vez: só preenche itens que ainda estão SEM categoria,
--  então o que a equipe já tiver ajustado pela tela é preservado.
-- =====================================================================

alter table public.stock_items add column if not exists categories text[] not null default '{}';
create index if not exists stock_items_categories_idx on public.stock_items using gin (categories);
comment on column public.stock_items.categories is 'Categorias do item (pode ter várias): Max Forte, Max Serviços, EPI, Acessório…';

drop table if exists _categorias_planilha;
create temp table _categorias_planilha (name text, size text, categories text[]);
insert into _categorias_planilha (name, size, categories) values
  ('ALgema de dobradiça', 'Único', array['Acessório']),
  ('Algema de dobradiça 2', 'Único', array['Acessório']),
  ('Apito', 'Único', array['Max Forte']),
  ('Apito c/ fiel', 'Único', array['Max Forte']),
  ('Boina', 'Único', array['Max Forte']),
  ('Capa para acento de moto', 'Único', array['Acessório']),
  ('Capacete Moto (adesivado)', '60', array['Acessório']),
  ('Cinto Niquelado', 'Único', array['Acessório']),
  ('Cinto Social', 'Único', array['Acessório']),
  ('Cinto Tático', 'Único', array['Acessório']),
  ('Empunhadura Révolver Taurus', 'Único', array['Acessório']),
  ('Fiel amarela', 'Único', array['Acessório']),
  ('Galão Água - 5L (Termolar)', 'Único', array['Acessório']),
  ('Gravata Azul - Lisa', 'Único', array['Acessório']),
  ('Gravata Preta - Lisa', 'Único', array['Acessório']),
  ('Oleo 2T Castrol 500ml P/ Roçadeira', 'Único', array['Acessório']),
  ('Capacete Obra Azul', 'Único', array['EPI']),
  ('Capacete Obra Branco', 'Único', array['EPI']),
  ('Capacete Obra Marron', 'Único', array['EPI']),
  ('Capacete Obra Verde', 'Único', array['EPI']),
  ('Colete Refletivo Jaqueta', 'Único', array['EPI']),
  ('Colete Refletivo X', 'Único', array['EPI']),
  ('Filtro para respirador', 'Único', array['EPI']),
  ('Luva Anticorte', 'EG', array['EPI']),
  ('Luva de Vaqueta', 'Único', array['EPI']),
  ('Luva Grip - Azul ou Preta', 'G', array['EPI']),
  ('Luva Látex - Amarela', 'M', array['EPI']),
  ('Luva Látex - Amarela', 'G', array['EPI']),
  ('Luva Látex - Azul', 'G', array['EPI']),
  ('Luva Látex - Azul', 'EG', array['EPI']),
  ('Luva Látex - Azul', 'M', array['EPI']),
  ('Luva Latex - Laranja', 'M', array['EPI']),
  ('Luva Látex Ranhurada Volk', 'G', array['EPI']),
  ('Luva Meio Dedo de Couro - Moto', 'GG', array['EPI']),
  ('Luva Pigmentada Preta', 'Único', array['EPI']),
  ('Luva PVC (Smart 36) - Verde', 'Único', array['EPI']),
  ('Máscara de Proteção PFF2 S', 'Único', array['EPI']),
  ('Máscaras de Pano', 'Único', array['EPI']),
  ('Óculos de Segurança Incolor', 'Único', array['EPI']),
  ('Óculos de Segurança Preto', 'Único', array['EPI']),
  ('Protetor Auricular', 'Único', array['EPI']),
  ('Protetor Facial Articulado', 'Único', array['EPI']),
  ('Protetor Solar 120ml FPS 30 (Nutriex)', 'Único', array['EPI']),
  ('Protetor Solar FPS 30 4L', null, array['EPI']),
  ('Respirador 1\4 - semi facial com filtro', 'Único', array['EPI']),
  ('Base de ombrelone', 'Único', array['Equipamento']),
  ('Bastão de Ronda', 'Único', array['Equipamento']),
  ('Bateria de bastao de Ronda', 'Único', array['Equipamento']),
  ('Baú p/ moto', 'Único', array['Equipamento']),
  ('Bottons p/ bastão de ronda', 'Único', array['Equipamento']),
  ('Cabo de chupeta', null, array['Equipamento']),
  ('Cabo Duplo USB', 'Único', array['Equipamento']),
  ('Cacete de madeira', 'Único', array['Equipamento']),
  ('Capa de Chuva Amarela', 'Único', array['Equipamento']),
  ('Capa de Chuva Descartável (p/ evento)', null, array['Equipamento']),
  ('Capa de Chuva Preta', 'Único', array['Equipamento']),
  ('Celular Básico (Nokia 106)', 'Único', array['Equipamento']),
  ('Cofre- Metal (Grande)', 'Único', array['Equipamento']),
  ('Detector de Metal (Lua Tec - LWJ58)', 'Único', array['Equipamento']),
  ('Giroflex Copo', 'Único', array['Equipamento']),
  ('Giroflex Parabrisa', 'Único', array['Equipamento']),
  ('Guarda Chuva', 'Único', array['Equipamento']),
  ('Lanterna Tática', 'Único', array['Equipamento']),
  ('Livro de Ocorrência (100 folhas - 200mm x 298mm)', 'Único', array['Equipamento']),
  ('Marmi Quent', 'Único', array['Equipamento']),
  ('Ombrelone Reformado 2,00mt', 'Único', array['Equipamento']),
  ('Ombrelone Reformado 2,40mt', 'Único', array['Equipamento']),
  ('Smatphone Galaxy A07', 'Único', array['Equipamento']),
  ('Suporte p/ botton', 'Único', array['Equipamento']),
  ('Totem', 'Único', array['Equipamento']),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '4', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '5', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '6', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '7', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '8', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '9', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', 'ESP', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '4', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '5', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '6', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '7', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '8', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '9', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', 'ESP', array['Higienizado', 'Max Forte']),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '4', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '5', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '6', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '7', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '8', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '9', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '4', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '5', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '6', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '7', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '9', array['Higienizado', 'Max Serviços']),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '10', array['Higienizado', 'Max Serviços']),
  ('Camisa Polo Preta - Max Confiável', 'M', array['Max Confiável']),
  ('Camisa Polo Preta - Max Confiável', 'G', array['Max Confiável']),
  ('Camisa Polo Preta - Max Confiável', 'GG', array['Max Confiável']),
  ('Camisa Social Amarela Operacional Masculina - Max Confiável', 'G', array['Max Confiável']),
  ('Boné Max Forte (Preto)', 'Único', array['Max Forte']),
  ('Camisa M/C Max Forte', '4', array['Max Forte']),
  ('Camisa M/C Max Forte', '5', array['Max Forte']),
  ('Camisa M/C Max Forte', '6', array['Max Forte']),
  ('Camisa M/C Max Forte', '7', array['Max Forte']),
  ('Camisa M/C Max Forte', '8', array['Max Forte']),
  ('Camisa M/C Max Forte', '9', array['Max Forte']),
  ('Camisa M/C Max Forte', '10', array['Max Forte']),
  ('Camisa M/C Max Forte', 'ESP 1', array['Max Forte']),
  ('Camisa M/C Max Forte', 'ESP 2', array['Max Forte']),
  ('Camisa M/L Max Forte', '4', array['Max Forte']),
  ('Camisa M/L Max Forte', '5', array['Max Forte']),
  ('Camisa M/L Max Forte', '6', array['Max Forte']),
  ('Camisa M/L Max Forte', '7', array['Max Forte']),
  ('Camisa M/L Max Forte', '8', array['Max Forte']),
  ('Camisa M/L Max Forte', '9', array['Max Forte']),
  ('Camisa M/L Max Forte', '10', array['Max Forte']),
  ('Camisa M/L Max Forte', 'ESP 1', array['Max Forte']),
  ('Camisa M/L Max Forte', 'ESP 2', array['Max Forte']),
  ('Camisa Polo Branca - Jovem Aprendiz', 'P', array['Max Forte']),
  ('Camisa Polo Branca - Jovem Aprendiz', 'M', array['Max Forte']),
  ('Camisa Polo Branca - Jovem Aprendiz', 'G', array['Max Forte']),
  ('Camisa Polo Branca - Jovem Aprendiz', 'GG', array['Max Forte']),
  ('Camisa Polo Branca - Jovem Aprendiz', 'EXG', array['Max Forte']),
  ('Camisa Polo Branca Masculina c\ Bordado 25 anos', 'ESP 1', array['Max Forte']),
  ('Camisa Polo Branca Masculina c\ Bordado 25 anos', null, array['Max Forte']),
  ('Camisa Social Branca - Max Forte', '2', array['Max Forte']),
  ('Camisa Social Branca - Max Forte', '3', array['Max Forte']),
  ('Camisa Social Branca - Max Forte', '7', array['Max Forte']),
  ('Capa de Chuva Preta (c/ logo) - Motoqueiro', 'EG', array['Acessório']),
  ('Capa de Chuva Preta (c/ logo) - Motoqueiro', 'G', array['Acessório']),
  ('Capa de Chuva Preta (c/ logo) - Motoqueiro', 'M', array['Acessório']),
  ('Capa de Colete Max Forte', 'G,GG,XG', array['Max Forte']),
  ('Capa de Colete Max Forte', 'M', array['Max Forte']),
  ('Capa de Colete Max Forte', 'P', array['Max Forte']),
  ('Coturno', '36', array['Max Forte']),
  ('Coturno', '37', array['Max Forte']),
  ('Coturno', '38', array['Max Forte']),
  ('Coturno', '39', array['Max Forte']),
  ('Coturno', '40', array['Max Forte']),
  ('Coturno', '41', array['Max Forte']),
  ('Coturno', '42', array['Max Forte']),
  ('Coturno', '43', array['Max Forte']),
  ('Coturno', '44', array['Max Forte']),
  ('Coturno', '45', array['Max Forte']),
  ('Coturno', '46', array['Max Forte']),
  ('Coturno', '47', array['Max Forte']),
  ('Coturno', '48', array['Max Forte']),
  ('Coturno', '50', array['Max Forte']),
  ('Jaqueta Corta-Vento - Preta', 'G', array['Max Forte']),
  ('Kit Proteção Moto - c/ joelheira e cotoveleira', 'Único', array['Max Forte']),
  ('Paletó Masculino - Max Forte', null, array['Max Forte']),
  ('Porta Tonfa', null, array['Max Forte']),
  ('Spray de Defesa Pessoal', 'Único', array['Max Forte']),
  ('Tonfa fixa', 'Único', array['Max Forte']),
  ('Avental - Branco com Bolso (Max Serviços Bordado)', 'Único', array['Max Serviços']),
  ('Avental de raspa em couro Jardineiro', 'Único', array['Max Serviços']),
  ('Blazer Ferminino', '42', array['Max Serviços']),
  ('Blazer Ferminino', '46', array['Max Serviços']),
  ('Boné Arabe Max Serviços (Marrom)', 'Único', array['Max Serviços']),
  ('Boné Max Serviços (Marrom)', 'Único', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '35', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '36', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '37', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '38', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '39', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '40', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '41', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '42', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '43', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '44', array['Max Serviços']),
  ('Bota Sete Léguas - PVC', '46', array['Max Serviços']),
  ('Botina com Biqueira', '34', array['Max Serviços']),
  ('Botina com Biqueira', '35', array['Max Serviços']),
  ('Botina com Biqueira', '37', array['Max Serviços']),
  ('Botina com Biqueira', '38', array['Max Serviços']),
  ('Botina com Biqueira', '39', array['Max Serviços']),
  ('Botina com Biqueira', '40', array['Max Serviços']),
  ('Botina com Biqueira', '41', array['Max Serviços']),
  ('Botina com Biqueira', '42', array['Max Serviços']),
  ('Botina com Biqueira', '43', array['Max Serviços']),
  ('Botina com Biqueira', '44', array['Max Serviços']),
  ('Botina com Biqueira', '45', array['Max Serviços']),
  ('Botina com Biqueira', '46', array['Max Serviços']),
  ('Botina com Biqueira', '47', array['Max Serviços']),
  ('Botina com Biqueira', '48', array['Max Serviços']),
  ('Botina com Biqueira', '49', array['Max Serviços']),
  ('Botina com Biqueira', '50', array['Max Serviços']),
  ('Calça Eletricista - Cinza c\ faixa refletiva (Anti-Chamas)', 'G', array['Max Serviços']),
  ('Calça Social - Feminino', '44', array['Max Serviços']),
  ('Calça Social - Feminino', '54', array['Max Serviços']),
  ('Calça Social - Feminino', '40', array['Max Serviços']),
  ('Calça Social - Feminino', '42', array['Max Serviços']),
  ('Calça Social - Feminino', 'G', array['Max Serviços']),
  ('Calça Social - Feminino', 'GG', array['Max Serviços']),
  ('Calça Social - Feminino', '50', array['Max Serviços']),
  ('Calça Social - Feminino', '46', array['Max Serviços']),
  ('Calça Social - Feminino', '48', array['Max Serviços']),
  ('Calça Social - Feminino', '52', array['Max Serviços']),
  ('Calça Social - Masculino', '36', array['Max Serviços']),
  ('Calça Social - Masculino', '38', array['Max Serviços']),
  ('Calça Social - Masculino', '40', array['Max Serviços']),
  ('Calça Social - Masculino', '42', array['Max Serviços']),
  ('Calça Social - Masculino', '44', array['Max Serviços']),
  ('Calça Social - Masculino', '46', array['Max Serviços']),
  ('Calça Social - Masculino', '48', array['Max Serviços']),
  ('Calça Social - Masculino', '50', array['Max Serviços']),
  ('Calça Social - Masculino', '52', array['Max Serviços']),
  ('Calça Social - Masculino', '54', array['Max Serviços']),
  ('Calça Social - Masculino', '56', array['Max Serviços']),
  ('Calça Social - Masculino', '58', array['Max Serviços']),
  ('Calça Social - Masculino', '60', array['Max Serviços']),
  ('Calça Social - Masculino', '62', array['Max Serviços']),
  ('Calça Social - Masculino', '64', array['Max Serviços']),
  ('Calça Social - Masculino', '66', array['Max Serviços']),
  ('Camisa Eletricista - Cinza c\ faixa refletiva (Anti-Chamas) - M\L', 'G', array['Max Serviços']),
  ('Camisa M/C Max Serviços', '4', array['Max Serviços']),
  ('Camisa M/C Max Serviços', '5', array['Max Serviços']),
  ('Camisa M/C Max Serviços', '6', array['Max Serviços']),
  ('Camisa M/C Max Serviços', '7', array['Max Serviços']),
  ('Camisa M/C Max Serviços', '8', array['Max Serviços']),
  ('Camisa M/C Max Serviços', '9', array['Max Serviços']),
  ('Camisa M/C Max Serviços', '10', array['Max Serviços']),
  ('Camisa M/C Max Serviços', 'ESP 1', array['Max Serviços']),
  ('Camisa M/C Max Serviços', 'ESP 2', array['Max Serviços']),
  ('Camisa M/L Max Serviços', '4', array['Max Serviços']),
  ('Camisa M/L Max Serviços', '5', array['Max Serviços']),
  ('Camisa M/L Max Serviços', '6', array['Max Serviços']),
  ('Camisa M/L Max Serviços', '7', array['Max Serviços']),
  ('Camisa M/L Max Serviços', '8', array['Max Serviços']),
  ('Camisa M/L Max Serviços', '9', array['Max Serviços']),
  ('Camisa M/L Max Serviços', '10', array['Max Serviços']),
  ('Camisa M/L Max Serviços', 'ESP 1', array['Max Serviços']),
  ('Camisa M/L Max Serviços', 'ESP 2', array['Max Serviços']),
  ('Camisa Marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'M', array['Max Serviços']),
  ('Camisa Marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'G', array['Max Serviços']),
  ('Camisa Social Branca Masculina - Max Serviços - M\C', 'XG', array['Max Serviços']),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '2', array['Max Serviços']),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '3', array['Max Serviços']),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '4', array['Max Serviços']),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '5', array['Max Serviços']),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '6', array['Max Serviços']),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '7', array['Max Serviços']),
  ('Camisa social Feminina 3/4 Branca', 'P', array['Max Serviços']),
  ('Camisa social Feminina 3/4 Branca', 'M', array['Max Serviços']),
  ('Camisa social Feminina 3/4 Branca', 'G', array['Max Serviços']),
  ('Camisa social Feminina 3/4 Branca', 'GG', array['Max Serviços']),
  ('Camisa social Feminina 3/4 Branca', 'XG', array['Max Serviços']),
  ('Cinta Ergonomica Abdominal com Suspensório', 'G', array['Max Serviços']),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'M', array['Max Serviços']),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'G', array['Max Serviços']),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'GG', array['Max Serviços']),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'P', array['Max Serviços']),
  ('Conjunto ASG', 'M', array['Max Serviços']),
  ('Conjunto ASG', 'P', array['Max Serviços']),
  ('Conjunto ASG', 'G', array['Max Serviços']),
  ('Conjunto ASG', 'GG', array['Max Serviços']),
  ('Conjunto ASG', 'XG', array['Max Serviços']),
  ('Conjunto eletricista c/ faixa refletiva - Eletricista', 'P', array['Max Serviços']),
  ('Paletó Masculino - Serviços', null, array['Max Serviços']),
  ('Perneira (Couro)', 'Único', array['Max Serviços']),
  ('Perneira (Preta)', 'Único', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '34', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '35', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '36', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '37', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '38', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '39', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '40', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '41', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '42', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '43', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '44', array['Max Serviços']),
  ('Sapato ASG Antiderrapante Unisex', '45', array['Max Serviços']),
  ('Sapato Social Feminino', '34', array['Max Serviços']),
  ('Sapato Social Feminino', '35', array['Max Serviços']),
  ('Sapato Social Feminino', '36', array['Max Serviços']),
  ('Sapato Social Feminino', '37', array['Max Serviços']),
  ('Sapato Social Feminino', '38', array['Max Serviços']),
  ('Sapato Social Feminino', '39', array['Max Serviços']),
  ('Sapato Social Feminino', '40', array['Max Serviços']),
  ('Sapato Social Feminino', '41', array['Max Serviços']),
  ('Sapato Social Feminino', '42', array['Max Serviços']),
  ('Sapato Social Feminino', '43', array['Max Serviços']),
  ('Sapato Social Masculino', '38', array['Max Serviços']),
  ('Sapato Social Masculino', '39', array['Max Serviços']),
  ('Sapato Social Masculino', '40', array['Max Serviços']),
  ('Sapato Social Masculino', '41', array['Max Serviços']),
  ('Sapato Social Masculino', '42', array['Max Serviços']),
  ('Sapato Social Masculino', '43', array['Max Serviços']),
  ('Sapato Social Masculino', '44', array['Max Serviços']),
  ('Sapato Social Masculino', '45', array['Max Serviços']),
  ('Sapato Social Masculino', '46', array['Max Serviços']),
  ('Sapato Social Masculino', '47', array['Max Serviços']),
  ('Touca ASG', 'Único', array['Max Serviços']),
  ('Calça Operacional', '42', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '44', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '46', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '48', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '50', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '52', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '54', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '56', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '58', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '60', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '62', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '64', array['Max Serviços', 'Max Forte']),
  ('Calça Operacional', '66', array['Max Serviços', 'Max Forte']);

update public.stock_items i
   set categories = p.categories
  from _categorias_planilha p
 where i.name_key = lower(btrim(p.name))
   and i.size_key = lower(btrim(coalesce(p.size, '')))
   and i.categories = '{}';

drop table if exists _categorias_planilha;
notify pgrst, 'reload schema';

-- Conferência: quantos itens ficaram em cada categoria (a última linha mostra os que ficaram sem nenhuma).
select c.categoria, count(*) as itens, coalesce(sum(c.quantity), 0) as unidades_no_almoxarifado
  from (
    select unnest(case when categories = '{}' then array['(sem categoria)'] else categories end) as categoria, quantity
      from public.stock_items
  ) c
 group by c.categoria
 order by (c.categoria = '(sem categoria)'), count(*) desc;
