-- =====================================================================
--  Almoxarifado · Correção do estoque pela planilha Livro2.xlsx
--  Cole TODO este arquivo no SQL Editor do Supabase e clique em "Run".
--  Use em um banco que já tem itens carregados (seed_estoque.sql antigo).
--
--  O que faz:
--    1. Acerta quantidade (saldo), estoque mínimo, custo e unidade dos itens
--       que já existem (mesmo nome + tamanho) para os valores da planilha.
--    2. Cada quantidade alterada vira um registro "ajuste" no histórico
--       de movimentações (com o antes e o depois).
--    3. Cadastra os itens da planilha que ainda não existem.
--    Não apaga nenhum item, posto, envio a posto ou movimentação.
--  Pode rodar mais de uma vez: na segunda vez não há nada a alterar.
-- =====================================================================

drop table if exists _estoque_planilha;
create temp table _estoque_planilha (
  name         text,
  size         text,
  unit         text,
  quantity     integer,
  min_quantity integer,
  cost         numeric(12,2)
);

insert into _estoque_planilha (name, size, unit, quantity, min_quantity, cost) values
  ('ALgema de dobradiça', 'Único', 'Par', 4, 0, 190.0),
  ('Algema de dobradiça 2', 'Único', 'Par', 0, 0, 120.99),
  ('Apito', 'Único', 'Cada', 3, 0, 2.58),
  ('Apito c/ fiel', 'Único', 'Cada', 39, 30, 13.69),
  ('Avental - Branco com Bolso (Max Serviços Bordado)', 'Único', 'Cada', 67, 10, 36.36),
  ('Avental de raspa em couro Jardineiro', 'Único', 'Cada', 4, 3, 35.0),
  ('Base de ombrelone', 'Único', 'Cada', 7, 4, 290.0),
  ('Bastão de Ronda', 'Único', 'Cada', 5, 2, 393.59),
  ('Bateria de bastao de Ronda', 'Único', 'Cada', 0, 4, 80.0),
  ('Baú p/ moto', 'Único', 'Cada', 5, 2, 130.0),
  ('Blazer Ferminino', '42', 'Cada', 1, 1, null),
  ('Blazer Ferminino', '46', 'Cada', 0, 1, null),
  ('Boina', 'Único', 'Cada', 2, 0, 114.5),
  ('Boné Arabe Max Serviços (Marrom)', 'Único', 'Cada', 0, 10, 21.9),
  ('Boné Max Forte (Preto)', 'Único', 'Cada', 13, 50, 17.0),
  ('Boné Max Serviços (Marrom)', 'Único', 'Cada', 0, 50, 17.0),
  ('Bota Sete Léguas - PVC', '35', 'Par', 6, 1, 49.9),
  ('Bota Sete Léguas - PVC', '36', 'Par', 2, 1, 49.9),
  ('Bota Sete Léguas - PVC', '37', 'Par', 9, 2, 49.9),
  ('Bota Sete Léguas - PVC', '38', 'Par', 9, 2, 49.9),
  ('Bota Sete Léguas - PVC', '39', 'Par', 9, 2, 49.9),
  ('Bota Sete Léguas - PVC', '40', 'Par', 5, 2, 49.9),
  ('Bota Sete Léguas - PVC', '41', 'Par', 7, 2, 49.9),
  ('Bota Sete Léguas - PVC', '42', 'Par', 1, 2, 49.9),
  ('Bota Sete Léguas - PVC', '43', 'Par', 0, 2, 49.9),
  ('Bota Sete Léguas - PVC', '44', 'Par', 3, 1, 49.9),
  ('Bota Sete Léguas - PVC', '46', 'Par', 1, 1, 49.9),
  ('Botina com Biqueira', '34', 'Par', 4, 2, 45.9),
  ('Botina com Biqueira', '35', 'Par', 4, 3, 45.9),
  ('Botina com Biqueira', '37', 'Par', 0, 3, 45.9),
  ('Botina com Biqueira', '38', 'Par', 2, 5, 45.9),
  ('Botina com Biqueira', '39', 'Par', 0, 8, 45.9),
  ('Botina com Biqueira', '40', 'Par', 1, 10, 45.9),
  ('Botina com Biqueira', '41', 'Par', 3, 10, 45.9),
  ('Botina com Biqueira', '42', 'Par', 0, 15, 45.9),
  ('Botina com Biqueira', '43', 'Par', 2, 15, 45.9),
  ('Botina com Biqueira', '44', 'Par', 3, 15, 45.9),
  ('Botina com Biqueira', '45', 'Par', 0, 5, 45.9),
  ('Botina com Biqueira', '46', 'Par', 0, 3, 45.9),
  ('Botina com Biqueira', '47', 'Par', 0, 3, 45.9),
  ('Botina com Biqueira', '48', 'Par', 0, 2, 45.9),
  ('Botina com Biqueira', '49', 'Par', 0, 1, 45.9),
  ('Botina com Biqueira', '50', 'Par', 0, 1, 45.9),
  ('Bottons p/ bastão de ronda', 'Único', 'Cada', 49, 18, 12.26),
  ('Cabo de chupeta', null, 'Cada', 0, 0, null),
  ('Cabo Duplo USB', 'Único', 'Cada', 33, 0, 17.0),
  ('Cacete de madeira', 'Único', 'Cada', 0, 0, 30.0),
  ('Calça Eletricista - Cinza c\ faixa refletiva (Anti-Chamas)', 'G', 'Cada', 2, 0, 130.65),
  ('Calça Operacional', '42', 'Cada', 0, 10, 84.76),
  ('Calça Operacional', '44', 'Cada', 2, 25, 84.76),
  ('Calça Operacional', '46', 'Cada', 36, 25, 84.76),
  ('Calça Operacional', '48', 'Cada', 36, 15, 84.76),
  ('Calça Operacional', '50', 'Cada', 39, 10, 84.76),
  ('Calça Operacional', '52', 'Cada', 4, 5, 84.76),
  ('Calça Operacional', '54', 'Cada', 1, 8, 84.76),
  ('Calça Operacional', '56', 'Cada', 8, 5, 81.2),
  ('Calça Operacional', '58', 'Cada', 10, 5, 93.38),
  ('Calça Operacional', '60', 'Cada', 0, 3, 93.38),
  ('Calça Operacional', '62', 'Cada', 0, 3, 93.38),
  ('Calça Operacional', '64', 'Cada', 0, 6, 93.38),
  ('Calça Operacional', '66', 'Cada', 10, 3, 93.38),
  ('Calça Social - Feminino', '44', 'Cada', 0, 6, 79.6),
  ('Calça Social - Feminino', '54', 'Cada', 6, 4, 79.6),
  ('Calça Social - Feminino', '40', 'Cada', 1, 4, 79.6),
  ('Calça Social - Feminino', '42', 'Cada', 0, 4, 79.6),
  ('Calça Social - Feminino', 'G', 'Cada', 0, 2, 68.0),
  ('Calça Social - Feminino', 'GG', 'Cada', 0, 2, 68.0),
  ('Calça Social - Feminino', '50', 'Cada', 2, 2, 68.0),
  ('Calça Social - Feminino', '46', 'Cada', 0, 8, 77.5),
  ('Calça Social - Feminino', '48', 'Cada', 0, 8, 77.5),
  ('Calça Social - Feminino', '52', 'Cada', 2, 4, 79.6),
  ('Calça Social - Masculino', '36', 'Cada', 0, 5, 90.0),
  ('Calça Social - Masculino', '38', 'Cada', 0, 4, 81.18),
  ('Calça Social - Masculino', '40', 'Cada', 0, 4, 81.18),
  ('Calça Social - Masculino', '42', 'Cada', 8, 5, 65.0),
  ('Calça Social - Masculino', '44', 'Cada', 6, 8, 65.0),
  ('Calça Social - Masculino', '46', 'Cada', 4, 8, 65.0),
  ('Calça Social - Masculino', '48', 'Cada', 0, 5, 65.0),
  ('Calça Social - Masculino', '50', 'Cada', 3, 5, 65.0),
  ('Calça Social - Masculino', '52', 'Cada', 9, 5, 90.0),
  ('Calça Social - Masculino', '54', 'Cada', 13, 5, 90.0),
  ('Calça Social - Masculino', '56', 'Cada', 6, 5, 90.0),
  ('Calça Social - Masculino', '58', 'Cada', 4, 5, 90.0),
  ('Calça Social - Masculino', '60', 'Cada', 4, 5, 90.0),
  ('Calça Social - Masculino', '62', 'Cada', 2, 5, 90.0),
  ('Calça Social - Masculino', '64', 'Cada', 9, 5, 90.0),
  ('Calça Social - Masculino', '66', 'Cada', 6, 5, 90.0),
  ('Camisa Eletricista - Cinza c\ faixa refletiva (Anti-Chamas) - M\L', 'G', 'Cada', 2, 5, 157.3),
  ('Camisa M/C Max Forte', '4', 'Cada', 32, 30, 77.99),
  ('Camisa M/C Max Forte', '5', 'Cada', 25, 25, 77.99),
  ('Camisa M/C Max Forte', '6', 'Cada', 18, 20, 81.41),
  ('Camisa M/C Max Forte', '7', 'Cada', 14, 10, 77.99),
  ('Camisa M/C Max Forte', '8', 'Cada', 27, 8, 77.99),
  ('Camisa M/C Max Forte', '9', 'Cada', 30, 8, 77.99),
  ('Camisa M/C Max Forte', '10', 'Cada', 24, 6, 77.99),
  ('Camisa M/C Max Forte', 'ESP 1', 'Cada', 29, 3, 81.0),
  ('Camisa M/C Max Forte', 'ESP 2', 'Cada', 21, 3, 81.0),
  ('Camisa M/C Max Serviços', '4', 'Cada', 2, 40, 73.06),
  ('Camisa M/C Max Serviços', '5', 'Cada', 22, 30, 69.99),
  ('Camisa M/C Max Serviços', '6', 'Cada', 19, 20, 69.99),
  ('Camisa M/C Max Serviços', '7', 'Cada', 24, 10, 69.99),
  ('Camisa M/C Max Serviços', '8', 'Cada', 17, 6, 69.99),
  ('Camisa M/C Max Serviços', '9', 'Cada', 42, 2, 69.99),
  ('Camisa M/C Max Serviços', '10', 'Cada', 22, 2, 69.99),
  ('Camisa M/C Max Serviços', 'ESP 1', 'Cada', 16, 2, 71.0),
  ('Camisa M/C Max Serviços', 'ESP 2', 'Cada', 7, 2, 71.0),
  ('Camisa M/L Max Forte', '4', 'Cada', 29, 40, 90.66),
  ('Camisa M/L Max Forte', '5', 'Cada', 18, 30, 94.64),
  ('Camisa M/L Max Forte', '6', 'Cada', 10, 20, 94.64),
  ('Camisa M/L Max Forte', '7', 'Cada', 30, 10, 90.66),
  ('Camisa M/L Max Forte', '8', 'Cada', 19, 10, 104.25),
  ('Camisa M/L Max Forte', '9', 'Cada', 27, 10, 104.25),
  ('Camisa M/L Max Forte', '10', 'Cada', 16, 6, 104.25),
  ('Camisa M/L Max Forte', 'ESP 1', 'Cada', 1, 2, 71.0),
  ('Camisa M/L Max Forte', 'ESP 2', 'Cada', 6, 2, 71.0),
  ('Camisa M/L Max Serviços', '4', 'Cada', 2, 30, 90.06),
  ('Camisa M/L Max Serviços', '5', 'Cada', 8, 20, 82.66),
  ('Camisa M/L Max Serviços', '6', 'Cada', 8, 20, 90.06),
  ('Camisa M/L Max Serviços', '7', 'Cada', 6, 15, 82.61),
  ('Camisa M/L Max Serviços', '8', 'Cada', 12, 6, 82.61),
  ('Camisa M/L Max Serviços', '9', 'Cada', 14, 5, 82.61),
  ('Camisa M/L Max Serviços', '10', 'Cada', 19, 3, 82.61),
  ('Camisa M/L Max Serviços', 'ESP 1', 'Cada', 28, 2, 71.0),
  ('Camisa M/L Max Serviços', 'ESP 2', 'Cada', 5, 2, 71.0),
  ('Camisa Marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'M', 'Cada', 1, 6, 73.2),
  ('Camisa Marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'G', 'Cada', 0, 6, 73.2),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '4', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '5', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '6', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '7', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '8', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '9', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', 'ESP', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '4', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '5', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '6', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '7', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '8', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '9', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', 'ESP', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '4', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '5', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '6', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '7', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '8', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '9', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '4', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '5', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '6', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '7', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '9', 'Cada', 0, 0, null),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '10', 'Cada', 0, 0, null),
  ('Camisa Polo Branca - Jovem Aprendiz', 'P', 'Cada', 1, 0, 53.8),
  ('Camisa Polo Branca - Jovem Aprendiz', 'M', 'Cada', 13, 0, 53.8),
  ('Camisa Polo Branca - Jovem Aprendiz', 'G', 'Cada', 10, 0, 53.8),
  ('Camisa Polo Branca - Jovem Aprendiz', 'GG', 'Cada', 7, 0, 53.8),
  ('Camisa Polo Branca - Jovem Aprendiz', 'EXG', 'Cada', 2, 0, 53.8),
  ('Camisa Polo Branca Masculina c\ Bordado 25 anos', 'ESP 1', 'Cada', 1, 0, 53.8),
  ('Camisa Polo Branca Masculina c\ Bordado 25 anos', null, 'Cada', 0, 0, null),
  ('Camisa Polo Preta - Max Confiável', 'M', 'Cada', 2, 0, 41.9),
  ('Camisa Polo Preta - Max Confiável', 'G', 'Cada', 2, 0, 41.9),
  ('Camisa Polo Preta - Max Confiável', 'GG', 'Cada', 2, 0, 41.9),
  ('Camisa Social Amarela Operacional Masculina - Max Confiável', 'G', 'Cada', 0, 0, 45.0),
  ('Camisa Social Branca - Max Forte', '2', 'Cada', 0, 0, 93.96),
  ('Camisa Social Branca - Max Forte', '3', 'Cada', 0, 0, 93.96),
  ('Camisa Social Branca - Max Forte', '7', 'Cada', 0, 5, 79.82),
  ('Camisa Social Branca Masculina - Max Serviços - M\C', 'XG', 'Cada', 0, 0, 79.82),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '2', 'Cada', 0, 4, 74.7),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '3', 'Cada', 1, 8, 74.7),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '4', 'Cada', 10, 12, 74.7),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '5', 'Cada', 3, 8, 74.7),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '6', 'Cada', 4, 6, 98.9),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '7', 'Cada', 0, 4, 98.9),
  ('Camisa social Feminina 3/4 Branca', 'P', 'Cada', 0, 6, 74.7),
  ('Camisa social Feminina 3/4 Branca', 'M', 'Cada', 0, 8, 74.7),
  ('Camisa social Feminina 3/4 Branca', 'G', 'Cada', 0, 12, 74.7),
  ('Camisa social Feminina 3/4 Branca', 'GG', 'Cada', 0, 8, 74.7),
  ('Camisa social Feminina 3/4 Branca', 'XG', 'Cada', 0, 6, 74.7),
  ('Capa de Chuva Amarela', 'Único', 'Cada', 9, 0, 33.0),
  ('Capa de Chuva Descartável (p/ evento)', null, 'Cada', 230, 0, 7.0),
  ('Capa de Chuva Preta', 'Único', 'Cada', 0, 0, 49.0),
  ('Capa de Chuva Preta (c/ logo) - Motoqueiro', 'EG', 'Cada', 1, 0, 150.0),
  ('Capa de Chuva Preta (c/ logo) - Motoqueiro', 'G', 'Cada', 1, 0, 150.0),
  ('Capa de Chuva Preta (c/ logo) - Motoqueiro', 'M', 'Cada', 2, 0, 150.0),
  ('Capa de Colete Max Forte', 'G,GG,XG', 'Cada', 1, 50, 90.0),
  ('Capa de Colete Max Forte', 'M', 'Cada', 0, 0, null),
  ('Capa de Colete Max Forte', 'P', 'Cada', 0, 0, null),
  ('Capa para acento de moto', 'Único', 'Cada', 0, 0, 44.99),
  ('Capacete Moto (adesivado)', '60', 'Cada', 4, 6, 140.0),
  ('Capacete Obra Azul', 'Único', 'Cada', 0, 0, 15.0),
  ('Capacete Obra Branco', 'Único', 'Cada', 0, 0, 15.0),
  ('Capacete Obra Marron', 'Único', 'Cada', 2, 0, 15.0),
  ('Capacete Obra Verde', 'Único', 'Cada', 0, 0, 13.3),
  ('Celular Básico (Nokia 106)', 'Único', 'Cada', 5, 0, 120.0),
  ('Cinta Ergonomica Abdominal com Suspensório', 'G', 'Cada', 10, 0, 40.0),
  ('Cinto Niquelado', 'Único', 'Cada', 34, 50, 6.5),
  ('Cinto Social', 'Único', 'Cada', 0, 0, 25.0),
  ('Cinto Tático', 'Único', 'Cada', 7, 0, 100.0),
  ('Cofre- Metal (Grande)', 'Único', 'Cada', 2, 0, 500.0),
  ('Colete Refletivo Jaqueta', 'Único', 'Cada', 6, 0, 25.0),
  ('Colete Refletivo X', 'Único', 'Cada', 14, 0, 17.0),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'M', 'Cada', 1, 2, 117.7),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'G', 'Cada', 1, 2, 117.7),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'GG', 'Cada', 1, 2, 117.7),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'P', 'Cada', 0, 0, 134.8),
  ('Conjunto ASG', 'M', 'Par', 0, 10, 116.0),
  ('Conjunto ASG', 'P', 'Par', 0, 6, 116.0),
  ('Conjunto ASG', 'G', 'Par', 0, 10, 116.0),
  ('Conjunto ASG', 'GG', 'Par', 0, 6, 116.0),
  ('Conjunto ASG', 'XG', 'Par', 0, 4, 116.0),
  ('Conjunto eletricista c/ faixa refletiva - Eletricista', 'P', 'Par', 0, 1, 324.0),
  ('Coturno', '36', 'Par', 2, 2, 58.9),
  ('Coturno', '37', 'Par', 0, 1, 58.9),
  ('Coturno', '38', 'Par', 1, 2, 58.9),
  ('Coturno', '39', 'Par', 0, 2, 58.9),
  ('Coturno', '40', 'Par', 3, 8, 58.9),
  ('Coturno', '41', 'Par', 1, 12, 58.9),
  ('Coturno', '42', 'Par', 0, 15, 58.9),
  ('Coturno', '43', 'Par', 0, 15, 58.9),
  ('Coturno', '44', 'Par', 0, 15, 58.9),
  ('Coturno', '45', 'Par', 0, 10, 58.9),
  ('Coturno', '46', 'Par', 0, 8, 58.9),
  ('Coturno', '47', 'Par', 0, 5, 58.9),
  ('Coturno', '48', 'Par', 0, 3, 58.9),
  ('Coturno', '50', 'Par', 0, 2, 58.9),
  ('Detector de Metal (Lua Tec - LWJ58)', 'Único', 'Cada', 5, 2, 34.9),
  ('Empunhadura Révolver Taurus', 'Único', 'Cada', 2, 1, 84.43),
  ('Fiel amarela', 'Único', 'Cada', 0, 50, 11.11),
  ('Filtro para respirador', 'Único', 'Cada', 12, 6, 18.5),
  ('Galão Água - 5L (Termolar)', 'Único', 'Cada', 0, 0, 22.35),
  ('Giroflex Copo', 'Único', 'Cada', 8, 0, 72.0),
  ('Giroflex Parabrisa', 'Único', 'Cada', 0, 0, 109.0),
  ('Gravata Azul - Lisa', 'Único', 'Cada', 0, 5, 25.0),
  ('Gravata Preta - Lisa', 'Único', 'Cada', 0, 5, 25.42),
  ('Guarda Chuva', 'Único', 'Cada', 0, 2, 113.9),
  ('Jaqueta Corta-Vento - Preta', 'G', 'Cada', 5, 0, 65.0),
  ('Kit Proteção Moto - c/ joelheira e cotoveleira', 'Único', 'Cada', 1, 10, null),
  ('Lanterna Tática', 'Único', 'Cada', 3, 10, 30.53),
  ('Livro de Ocorrência (100 folhas - 200mm x 298mm)', 'Único', 'Cada', 75, 30, 11.3),
  ('Luva Anticorte', 'EG', 'Par', 5, 5, null),
  ('Luva de Vaqueta', 'Único', 'Par', 16, 15, 11.5),
  ('Luva Grip - Azul ou Preta', 'G', 'Par', 0, 15, 11.9),
  ('Luva Látex - Amarela', 'M', 'Par', 0, 25, 4.5),
  ('Luva Látex - Amarela', 'G', 'Par', 19, 25, 4.5),
  ('Luva Látex - Azul', 'G', 'Par', 0, 10, 10.56),
  ('Luva Látex - Azul', 'EG', 'Par', 0, 10, 10.56),
  ('Luva Látex - Azul', 'M', 'Par', 0, 10, 10.56),
  ('Luva Latex - Laranja', 'M', 'Par', 13, 0, 8.5),
  ('Luva Látex Ranhurada Volk', 'G', 'Par', 14, 20, 10.98),
  ('Luva Meio Dedo de Couro - Moto', 'GG', 'Par', 1, 1, 45.0),
  ('Luva Pigmentada Preta', 'Único', 'Par', 37, 20, 2.5),
  ('Luva PVC (Smart 36) - Verde', 'Único', 'Par', 13, 10, 21.45),
  ('Marmi Quent', 'Único', 'Cada', 0, 0, 125.0),
  ('Máscara de Proteção PFF2 S', 'Único', 'Cada', 100, 50, 0.9),
  ('Máscaras de Pano', 'Único', 'Par', 0, 0, 3.9),
  ('Óculos de Segurança Incolor', 'Único', 'Cada', 15, 15, 2.77),
  ('Óculos de Segurança Preto', 'Único', 'Cada', 43, 10, 2.77),
  ('Oleo 2T Castrol 500ml P/ Roçadeira', 'Único', 'Cada', 0, 5, 25.01),
  ('Ombrelone Reformado 2,00mt', 'Único', 'Cada', 3, 0, 390.0),
  ('Ombrelone Reformado 2,40mt', 'Único', 'Cada', 0, 0, 420.0),
  ('Paletó Masculino - Max Forte', null, 'Cada', 6, 0, 240.0),
  ('Paletó Masculino - Serviços', null, 'Cada', 2, 0, 240.0),
  ('Perneira (Couro)', 'Único', 'Par', 9, 2, 34.0),
  ('Perneira (Preta)', 'Único', 'Par', 0, 2, 40.0),
  ('Porta Tonfa', null, 'Cada', 9, 0, 26.0),
  ('Protetor Auricular', 'Único', 'Cada', 206, 50, 0.8),
  ('Protetor Facial Articulado', 'Único', 'Cada', 4, 2, 26.0),
  ('Protetor Solar 120ml FPS 30 (Nutriex)', 'Único', 'Cada', 5, 0, 15.0),
  ('Protetor Solar FPS 30 4L', null, 'Cada', 0, 0, 289.47),
  ('Respirador 1\4 - semi facial com filtro', 'Único', 'Cada', 2, 0, 24.74),
  ('Sapato ASG Antiderrapante Unisex', '34', 'Par', 5, 1, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '35', 'Par', 7, 1, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '36', 'Par', 14, 3, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '37', 'Par', 11, 2, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '38', 'Par', 12, 5, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '39', 'Par', 23, 3, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '40', 'Par', 19, 5, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '41', 'Par', 24, 3, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '42', 'Par', 7, 5, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '43', 'Par', 12, 3, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '44', 'Par', 4, 2, 58.4),
  ('Sapato ASG Antiderrapante Unisex', '45', 'Par', 2, 1, 58.4),
  ('Sapato Social Feminino', '34', 'Par', 4, 2, 49.95),
  ('Sapato Social Feminino', '35', 'Par', 4, 3, 49.95),
  ('Sapato Social Feminino', '36', 'Par', 4, 5, 49.95),
  ('Sapato Social Feminino', '37', 'Par', 7, 8, 49.95),
  ('Sapato Social Feminino', '38', 'Par', 0, 8, 49.95),
  ('Sapato Social Feminino', '39', 'Par', 0, 8, 49.95),
  ('Sapato Social Feminino', '40', 'Par', 1, 3, 49.95),
  ('Sapato Social Feminino', '41', 'Par', 0, 2, 49.95),
  ('Sapato Social Feminino', '42', 'Par', 3, 1, 49.95),
  ('Sapato Social Feminino', '43', 'Par', 3, 1, 49.95),
  ('Sapato Social Masculino', '38', 'Par', 0, 1, 59.76),
  ('Sapato Social Masculino', '39', 'Par', 2, 1, 59.76),
  ('Sapato Social Masculino', '40', 'Par', 3, 5, 59.76),
  ('Sapato Social Masculino', '41', 'Par', 1, 4, 59.76),
  ('Sapato Social Masculino', '42', 'Par', 0, 8, 59.76),
  ('Sapato Social Masculino', '43', 'Par', 0, 8, 59.76),
  ('Sapato Social Masculino', '44', 'Par', 1, 8, 59.76),
  ('Sapato Social Masculino', '45', 'Par', 0, 4, 59.76),
  ('Sapato Social Masculino', '46', 'Par', 2, 2, 59.76),
  ('Sapato Social Masculino', '47', 'Par', 1, 1, 59.76),
  ('Smatphone Galaxy A07', 'Único', 'Cada', 6, 2, 745.0),
  ('Spray de Defesa Pessoal', 'Único', 'Cada', 1, 1, 135.09),
  ('Suporte p/ botton', 'Único', 'Cada', 32, 15, null),
  ('Tonfa fixa', 'Único', 'Cada', 9, 5, 35.0),
  ('Totem', 'Único', 'Cada', 4, 5, 650.0),
  ('Touca ASG', 'Único', 'Cada', 8, 5, 33.0);

-- 1 + 2) histórico dos ajustes de quantidade e atualização dos itens que já existem
with alvo as (
  select i.id, i.name, i.size, i.quantity as antes, p.quantity as depois
    from public.stock_items i
    join _estoque_planilha p
      on i.name_key = lower(btrim(p.name))
     and i.size_key = lower(btrim(coalesce(p.size, '')))
   where i.quantity is distinct from p.quantity
), log as (
  insert into public.stock_movements
    (item_id, item_name, kind, quantity, before_qty, after_qty, note, by_name)
  select id,
         name || coalesce(' · ' || nullif(btrim(size), ''), ''),
         'ajuste', abs(depois - antes), antes, depois,
         'Correção pela planilha Livro2 (saldo)', 'Planilha'
    from alvo
  returning 1
)
select count(*) as quantidades_corrigidas from log;

update public.stock_items i
   set quantity     = p.quantity,
       min_quantity = p.min_quantity,
       cost         = p.cost,
       unit         = p.unit,
       updated_at   = now()
  from _estoque_planilha p
 where i.name_key = lower(btrim(p.name))
   and i.size_key = lower(btrim(coalesce(p.size, '')))
   and (i.quantity is distinct from p.quantity
     or i.min_quantity is distinct from p.min_quantity
     or i.cost is distinct from p.cost
     or i.unit is distinct from p.unit);

-- 3) itens da planilha que ainda não existem
insert into public.stock_items (name, size, unit, quantity, min_quantity, cost, created_by)
select p.name, p.size, p.unit, p.quantity, p.min_quantity, p.cost, 'Planilha'
  from _estoque_planilha p
 where not exists (
   select 1 from public.stock_items i
    where i.name_key = lower(btrim(p.name))
      and i.size_key = lower(btrim(coalesce(p.size, '')))
 );

drop table if exists _estoque_planilha;

-- Conferência: total de unidades no almoxarifado deve bater com a planilha
select count(*) as itens, sum(quantity) as unidades from public.stock_items;
