-- =====================================================================
--  Almoxarifado · Carga inicial do estoque (a partir da planilha Livro1.xlsx)
--  Rode DEPOIS de estoque.sql. Pode rodar mais de uma vez: itens que já
--  existem (mesmo nome e tamanho) são ignorados, nada é duplicado nem sobrescrito.
--  Itens: 308
-- =====================================================================

insert into public.stock_items (name, size, unit, quantity, min_quantity, cost, created_by) values
  ('ALgema de dobradiça', 'Único', 'Par', 4, 0, 190.0, 'Planilha'),
  ('Algema de dobradiça 2', 'Único', 'Par', 0, 0, 120.99, 'Planilha'),
  ('Apito', 'Único', 'Cada', 3, 0, 2.58, 'Planilha'),
  ('Apito c/ fiel', 'Único', 'Cada', 54, 30, 13.69, 'Planilha'),
  ('Avental - Branco com Bolso (Max Serviços Bordado)', 'Único', 'Cada', 67, 10, 36.36, 'Planilha'),
  ('Avental de raspa em couro Jardineiro', 'Único', 'Cada', 4, 3, 35.0, 'Planilha'),
  ('Base de ombrelone', 'Único', 'Cada', 7, 4, 290.0, 'Planilha'),
  ('Bastão de Ronda', 'Único', 'Cada', 2, 2, 393.59, 'Planilha'),
  ('Bateria de bastao de Ronda', 'Único', 'Cada', 1, 4, 80.0, 'Planilha'),
  ('Baú p/ moto', 'Único', 'Cada', 0, 2, 130.0, 'Planilha'),
  ('Blazer Ferminino', '42', 'Cada', 1, 1, null, 'Planilha'),
  ('Blazer Ferminino', '46', 'Cada', 1, 1, null, 'Planilha'),
  ('Boina', 'Único', 'Cada', 2, 0, 114.5, 'Planilha'),
  ('Boné Arabe Max Serviços (Marrom)', 'Único', 'Cada', 1, 10, 21.9, 'Planilha'),
  ('Boné Max Forte (Preto)', 'Único', 'Cada', 16, 50, 17.0, 'Planilha'),
  ('Boné Max Serviços (Marrom)', 'Único', 'Cada', 0, 50, 17.0, 'Planilha'),
  ('Bota Sete Léguas - PVC', '35', 'Par', 6, 1, 49.9, 'Planilha'),
  ('Bota Sete Léguas - PVC', '36', 'Par', 2, 1, 49.9, 'Planilha'),
  ('Bota Sete Léguas - PVC', '37', 'Par', 9, 2, 49.9, 'Planilha'),
  ('Bota Sete Léguas - PVC', '38', 'Par', 9, 2, 49.9, 'Planilha'),
  ('Bota Sete Léguas - PVC', '39', 'Par', 9, 2, 49.9, 'Planilha'),
  ('Bota Sete Léguas - PVC', '40', 'Par', 5, 2, 49.9, 'Planilha'),
  ('Bota Sete Léguas - PVC', '41', 'Par', 7, 2, 49.9, 'Planilha'),
  ('Bota Sete Léguas - PVC', '42', 'Par', 1, 2, 49.9, 'Planilha'),
  ('Bota Sete Léguas - PVC', '43', 'Par', 1, 2, 49.9, 'Planilha'),
  ('Bota Sete Léguas - PVC', '44', 'Par', 3, 1, 49.9, 'Planilha'),
  ('Bota Sete Léguas - PVC', '46', 'Par', 1, 1, 49.9, 'Planilha'),
  ('Botina com Biqueira', '34', 'Par', 4, 2, 45.9, 'Planilha'),
  ('Botina com Biqueira', '35', 'Par', 4, 3, 45.9, 'Planilha'),
  ('Botina com Biqueira', '37', 'Par', 0, 3, 45.9, 'Planilha'),
  ('Botina com Biqueira', '38', 'Par', 3, 5, 45.9, 'Planilha'),
  ('Botina com Biqueira', '39', 'Par', 2, 8, 45.9, 'Planilha'),
  ('Botina com Biqueira', '40', 'Par', 6, 10, 45.9, 'Planilha'),
  ('Botina com Biqueira', '41', 'Par', 9, 10, 45.9, 'Planilha'),
  ('Botina com Biqueira', '42', 'Par', 0, 15, 45.9, 'Planilha'),
  ('Botina com Biqueira', '43', 'Par', 0, 15, 45.9, 'Planilha'),
  ('Botina com Biqueira', '44', 'Par', 1, 15, 45.9, 'Planilha'),
  ('Botina com Biqueira', '45', 'Par', 2, 5, 45.9, 'Planilha'),
  ('Botina com Biqueira', '46', 'Par', 1, 3, 45.9, 'Planilha'),
  ('Botina com Biqueira', '47', 'Par', 0, 3, 45.9, 'Planilha'),
  ('Botina com Biqueira', '48', 'Par', 0, 2, 45.9, 'Planilha'),
  ('Botina com Biqueira', '49', 'Par', 0, 1, 45.9, 'Planilha'),
  ('Botina com Biqueira', '50', 'Par', 0, 1, 45.9, 'Planilha'),
  ('Bottons p/ bastão de ronda', 'Único', 'Cada', 25, 18, 12.26, 'Planilha'),
  ('Cabo de chupeta', null, 'Cada', 0, 0, null, 'Planilha'),
  ('Cabo Duplo USB', 'Único', 'Cada', 33, 0, 17.0, 'Planilha'),
  ('Cacete de madeira', 'Único', 'Cada', 0, 0, 30.0, 'Planilha'),
  ('Calça Eletricista - Cinza c\ faixa refletiva (Anti-Chamas)', 'G', 'Cada', 2, 0, 130.65, 'Planilha'),
  ('Calça Operacional', '42', 'Cada', 0, 10, 84.76, 'Planilha'),
  ('Calça Operacional', '44', 'Cada', 4, 25, 84.76, 'Planilha'),
  ('Calça Operacional', '46', 'Cada', 15, 25, 84.76, 'Planilha'),
  ('Calça Operacional', '48', 'Cada', 0, 15, 84.76, 'Planilha'),
  ('Calça Operacional', '50', 'Cada', 13, 10, 84.76, 'Planilha'),
  ('Calça Operacional', '52', 'Cada', 0, 5, 84.76, 'Planilha'),
  ('Calça Operacional', '54', 'Cada', 0, 8, 84.76, 'Planilha'),
  ('Calça Operacional', '56', 'Cada', 0, 5, 81.2, 'Planilha'),
  ('Calça Operacional', '58', 'Cada', 0, 5, 93.38, 'Planilha'),
  ('Calça Operacional', '60', 'Cada', 0, 3, 93.38, 'Planilha'),
  ('Calça Operacional', '62', 'Cada', 0, 3, 93.38, 'Planilha'),
  ('Calça Operacional', '64', 'Cada', 0, 6, 93.38, 'Planilha'),
  ('Calça Operacional', '66', 'Cada', 9, 3, 93.38, 'Planilha'),
  ('Calça Social - Feminino', '44', 'Cada', 0, 6, 79.6, 'Planilha'),
  ('Calça Social - Feminino', '54', 'Cada', 6, 4, 79.6, 'Planilha'),
  ('Calça Social - Feminino', '40', 'Cada', 3, 4, 79.6, 'Planilha'),
  ('Calça Social - Feminino', '42', 'Cada', 2, 4, 79.6, 'Planilha'),
  ('Calça Social - Feminino', 'G', 'Cada', 0, 2, 68.0, 'Planilha'),
  ('Calça Social - Feminino', 'GG', 'Cada', 0, 2, 68.0, 'Planilha'),
  ('Calça Social - Feminino', '50', 'Cada', 4, 2, 68.0, 'Planilha'),
  ('Calça Social - Feminino', '46', 'Cada', 0, 8, 77.5, 'Planilha'),
  ('Calça Social - Feminino', '48', 'Cada', 3, 8, 77.5, 'Planilha'),
  ('Calça Social - Feminino', '52', 'Cada', 2, 4, 79.6, 'Planilha'),
  ('Calça Social - Masculino', '36', 'Cada', 0, 5, 90.0, 'Planilha'),
  ('Calça Social - Masculino', '38', 'Cada', 0, 4, 81.18, 'Planilha'),
  ('Calça Social - Masculino', '40', 'Cada', 0, 4, 81.18, 'Planilha'),
  ('Calça Social - Masculino', '42', 'Cada', 0, 5, 65.0, 'Planilha'),
  ('Calça Social - Masculino', '44', 'Cada', 0, 8, 65.0, 'Planilha'),
  ('Calça Social - Masculino', '46', 'Cada', 0, 8, 65.0, 'Planilha'),
  ('Calça Social - Masculino', '48', 'Cada', 1, 5, 65.0, 'Planilha'),
  ('Calça Social - Masculino', '50', 'Cada', 3, 5, 65.0, 'Planilha'),
  ('Calça Social - Masculino', '52', 'Cada', 5, 5, 90.0, 'Planilha'),
  ('Calça Social - Masculino', '54', 'Cada', 13, 5, 90.0, 'Planilha'),
  ('Calça Social - Masculino', '56', 'Cada', 6, 5, 90.0, 'Planilha'),
  ('Calça Social - Masculino', '58', 'Cada', 3, 5, 90.0, 'Planilha'),
  ('Calça Social - Masculino', '60', 'Cada', 4, 5, 90.0, 'Planilha'),
  ('Calça Social - Masculino', '62', 'Cada', 2, 5, 90.0, 'Planilha'),
  ('Calça Social - Masculino', '64', 'Cada', 9, 5, 90.0, 'Planilha'),
  ('Calça Social - Masculino', '66', 'Cada', 6, 5, 90.0, 'Planilha'),
  ('Camisa Eletricista - Cinza c\ faixa refletiva (Anti-Chamas) - M\L', 'G', 'Cada', 2, 5, 157.3, 'Planilha'),
  ('Camisa M/C Max Forte', '4', 'Cada', 37, 30, 77.99, 'Planilha'),
  ('Camisa M/C Max Forte', '5', 'Cada', 30, 25, 77.99, 'Planilha'),
  ('Camisa M/C Max Forte', '6', 'Cada', 23, 20, 81.41, 'Planilha'),
  ('Camisa M/C Max Forte', '7', 'Cada', 17, 10, 77.99, 'Planilha'),
  ('Camisa M/C Max Forte', '8', 'Cada', 28, 8, 77.99, 'Planilha'),
  ('Camisa M/C Max Forte', '9', 'Cada', 30, 8, 77.99, 'Planilha'),
  ('Camisa M/C Max Forte', '10', 'Cada', 23, 6, 77.99, 'Planilha'),
  ('Camisa M/C Max Forte', 'ESP 1', 'Cada', 29, 3, 81.0, 'Planilha'),
  ('Camisa M/C Max Forte', 'ESP 2', 'Cada', 21, 3, 81.0, 'Planilha'),
  ('Camisa M/C Max Serviços', '4', 'Cada', 5, 40, 73.06, 'Planilha'),
  ('Camisa M/C Max Serviços', '5', 'Cada', 9, 30, 69.99, 'Planilha'),
  ('Camisa M/C Max Serviços', '6', 'Cada', 6, 20, 69.99, 'Planilha'),
  ('Camisa M/C Max Serviços', '7', 'Cada', 26, 10, 69.99, 'Planilha'),
  ('Camisa M/C Max Serviços', '8', 'Cada', 19, 6, 69.99, 'Planilha'),
  ('Camisa M/C Max Serviços', '9', 'Cada', 42, 2, 69.99, 'Planilha'),
  ('Camisa M/C Max Serviços', '10', 'Cada', 23, 2, 69.99, 'Planilha'),
  ('Camisa M/C Max Serviços', 'ESP 1', 'Cada', 16, 2, 71.0, 'Planilha'),
  ('Camisa M/C Max Serviços', 'ESP 2', 'Cada', 7, 2, 71.0, 'Planilha'),
  ('Camisa M/L Max Forte', '4', 'Cada', 21, 40, 90.66, 'Planilha'),
  ('Camisa M/L Max Forte', '5', 'Cada', 11, 30, 94.64, 'Planilha'),
  ('Camisa M/L Max Forte', '6', 'Cada', 2, 20, 94.64, 'Planilha'),
  ('Camisa M/L Max Forte', '7', 'Cada', 0, 10, 90.66, 'Planilha'),
  ('Camisa M/L Max Forte', '8', 'Cada', 5, 10, 104.25, 'Planilha'),
  ('Camisa M/L Max Forte', '9', 'Cada', 27, 10, 104.25, 'Planilha'),
  ('Camisa M/L Max Forte', '10', 'Cada', 16, 6, 104.25, 'Planilha'),
  ('Camisa M/L Max Forte', 'ESP 1', 'Cada', 1, 2, 71.0, 'Planilha'),
  ('Camisa M/L Max Forte', 'ESP 2', 'Cada', 6, 2, 71.0, 'Planilha'),
  ('Camisa M/L Max Serviços', '4', 'Cada', 5, 30, 90.06, 'Planilha'),
  ('Camisa M/L Max Serviços', '5', 'Cada', 17, 20, 82.66, 'Planilha'),
  ('Camisa M/L Max Serviços', '6', 'Cada', 10, 20, 90.06, 'Planilha'),
  ('Camisa M/L Max Serviços', '7', 'Cada', 8, 15, 82.61, 'Planilha'),
  ('Camisa M/L Max Serviços', '8', 'Cada', 15, 6, 82.61, 'Planilha'),
  ('Camisa M/L Max Serviços', '9', 'Cada', 14, 5, 82.61, 'Planilha'),
  ('Camisa M/L Max Serviços', '10', 'Cada', 20, 3, 82.61, 'Planilha'),
  ('Camisa M/L Max Serviços', 'ESP 1', 'Cada', 28, 2, 71.0, 'Planilha'),
  ('Camisa M/L Max Serviços', 'ESP 2', 'Cada', 5, 2, 71.0, 'Planilha'),
  ('Camisa Marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'M', 'Cada', 2, 6, 73.2, 'Planilha'),
  ('Camisa Marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'G', 'Cada', 3, 6, 73.2, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '4', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '5', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '6', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '7', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '8', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', '9', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Curta - Higienizada', 'ESP', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '4', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '5', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '6', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '7', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '8', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', '9', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Forte - Manga Longa - Higienizada', 'ESP', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '4', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '5', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '6', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '7', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '8', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Curta - Higienizada', '9', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '4', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '5', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '6', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '7', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '9', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Operacional Max Serviços - Manga Longa - Higienizada', '10', 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Polo Branca - Jovem Aprendiz', 'P', 'Cada', 1, 0, 53.8, 'Planilha'),
  ('Camisa Polo Branca - Jovem Aprendiz', 'M', 'Cada', 3, 0, 53.8, 'Planilha'),
  ('Camisa Polo Branca - Jovem Aprendiz', 'G', 'Cada', 5, 0, 53.8, 'Planilha'),
  ('Camisa Polo Branca - Jovem Aprendiz', 'GG', 'Cada', 7, 0, 53.8, 'Planilha'),
  ('Camisa Polo Branca - Jovem Aprendiz', 'EXG', 'Cada', 2, 0, 53.8, 'Planilha'),
  ('Camisa Polo Branca Masculina c\ Bordado 25 anos', 'ESP 1', 'Cada', 1, 0, 53.8, 'Planilha'),
  ('Camisa Polo Branca Masculina c\ Bordado 25 anos', null, 'Cada', 0, 0, null, 'Planilha'),
  ('Camisa Polo Preta - Max Confiável', 'M', 'Cada', 2, 0, 41.9, 'Planilha'),
  ('Camisa Polo Preta - Max Confiável', 'G', 'Cada', 2, 0, 41.9, 'Planilha'),
  ('Camisa Polo Preta - Max Confiável', 'GG', 'Cada', 2, 0, 41.9, 'Planilha'),
  ('Camisa Social Amarela Operacional Masculina - Max Confiável', 'G', 'Cada', 0, 0, 45.0, 'Planilha'),
  ('Camisa Social Branca - Max Forte', '2', 'Cada', 1, 0, 93.96, 'Planilha'),
  ('Camisa Social Branca - Max Forte', '3', 'Cada', 0, 0, 93.96, 'Planilha'),
  ('Camisa Social Branca - Max Forte', '7', 'Cada', 0, 5, 79.82, 'Planilha'),
  ('Camisa Social Branca Masculina - Max Serviços - M\C', 'XG', 'Cada', 0, 0, 79.82, 'Planilha'),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '2', 'Cada', 0, 4, 74.7, 'Planilha'),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '3', 'Cada', 0, 8, 74.7, 'Planilha'),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '4', 'Cada', 0, 12, 74.7, 'Planilha'),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '5', 'Cada', 0, 8, 74.7, 'Planilha'),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '6', 'Cada', 0, 6, 98.9, 'Planilha'),
  ('Camisa Social Branca Masculina - Max Serviços - M\L', '7', 'Cada', 0, 4, 98.9, 'Planilha'),
  ('Camisa social Feminina 3/4 Branca', 'P', 'Cada', 0, 6, 74.7, 'Planilha'),
  ('Camisa social Feminina 3/4 Branca', 'M', 'Cada', 0, 8, 74.7, 'Planilha'),
  ('Camisa social Feminina 3/4 Branca', 'G', 'Cada', 2, 12, 74.7, 'Planilha'),
  ('Camisa social Feminina 3/4 Branca', 'GG', 'Cada', 1, 8, 74.7, 'Planilha'),
  ('Camisa social Feminina 3/4 Branca', 'XG', 'Cada', 3, 6, 74.7, 'Planilha'),
  ('Capa de Chuva Amarela', 'Único', 'Cada', 11, 0, 33.0, 'Planilha'),
  ('Capa de Chuva Descartável (p/ evento)', null, 'Cada', 230, 0, 7.0, 'Planilha'),
  ('Capa de Chuva Preta', 'Único', 'Cada', 0, 0, 49.0, 'Planilha'),
  ('Capa de Chuva Preta (c/ logo) - Motoqueiro', 'EG', 'Cada', 1, 0, 150.0, 'Planilha'),
  ('Capa de Chuva Preta (c/ logo) - Motoqueiro', 'G', 'Cada', 1, 0, 150.0, 'Planilha'),
  ('Capa de Chuva Preta (c/ logo) - Motoqueiro', 'M', 'Cada', 2, 0, 150.0, 'Planilha'),
  ('Capa de Colete Max Forte', 'G,GG,XG', 'Cada', 1, 50, 90.0, 'Planilha'),
  ('Capa de Colete Max Forte', 'M', 'Cada', 0, 0, null, 'Planilha'),
  ('Capa de Colete Max Forte', 'P', 'Cada', 0, 0, null, 'Planilha'),
  ('Capa para acento de moto', 'Único', 'Cada', 0, 0, 44.99, 'Planilha'),
  ('Capacete Moto (adesivado)', '60', 'Cada', 4, 6, 140.0, 'Planilha'),
  ('Capacete Obra Azul', 'Único', 'Cada', 0, 0, 15.0, 'Planilha'),
  ('Capacete Obra Branco', 'Único', 'Cada', 0, 0, 15.0, 'Planilha'),
  ('Capacete Obra Marron', 'Único', 'Cada', 1, 0, 15.0, 'Planilha'),
  ('Capacete Obra Verde', 'Único', 'Cada', 0, 0, 13.3, 'Planilha'),
  ('Celular Básico (Nokia 106)', 'Único', 'Cada', 5, 0, 120.0, 'Planilha'),
  ('Cinta Ergonomica Abdominal com Suspensório', 'G', 'Cada', 10, 0, 40.0, 'Planilha'),
  ('Cinto Niquelado', 'Único', 'Cada', 63, 50, 6.5, 'Planilha'),
  ('Cinto Social', 'Único', 'Cada', 0, 0, 25.0, 'Planilha'),
  ('Cinto Tático', 'Único', 'Cada', 7, 0, 100.0, 'Planilha'),
  ('Cofre- Metal (Grande)', 'Único', 'Cada', 2, 0, 500.0, 'Planilha'),
  ('Colete Refletivo Jaqueta', 'Único', 'Cada', 6, 0, 25.0, 'Planilha'),
  ('Colete Refletivo X', 'Único', 'Cada', 0, 0, 17.0, 'Planilha'),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'M', 'Cada', 1, 2, 117.7, 'Planilha'),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'G', 'Cada', 3, 2, 117.7, 'Planilha'),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'GG', 'Cada', 1, 2, 117.7, 'Planilha'),
  ('Conj. marrom c\ faixa refletiva verde - Aux. Operacional - M\C', 'P', 'Cada', 0, 0, 134.8, 'Planilha'),
  ('Conjunto ASG', 'M', 'Par', 0, 10, 116.0, 'Planilha'),
  ('Conjunto ASG', 'P', 'Par', 2, 6, 116.0, 'Planilha'),
  ('Conjunto ASG', 'G', 'Par', 1, 10, 116.0, 'Planilha'),
  ('Conjunto ASG', 'GG', 'Par', 0, 6, 116.0, 'Planilha'),
  ('Conjunto ASG', 'XG', 'Par', 0, 4, 116.0, 'Planilha'),
  ('Conjunto eletricista c/ faixa refletiva - Eletricista', 'P', 'Par', 0, 1, 324.0, 'Planilha'),
  ('Coturno', '36', 'Par', 2, 2, 58.9, 'Planilha'),
  ('Coturno', '37', 'Par', 0, 1, 58.9, 'Planilha'),
  ('Coturno', '38', 'Par', 2, 2, 58.9, 'Planilha'),
  ('Coturno', '39', 'Par', 0, 2, 58.9, 'Planilha'),
  ('Coturno', '40', 'Par', 4, 8, 58.9, 'Planilha'),
  ('Coturno', '41', 'Par', 2, 12, 58.9, 'Planilha'),
  ('Coturno', '42', 'Par', 0, 15, 58.9, 'Planilha'),
  ('Coturno', '43', 'Par', 0, 15, 58.9, 'Planilha'),
  ('Coturno', '44', 'Par', 0, 15, 58.9, 'Planilha'),
  ('Coturno', '45', 'Par', 0, 10, 58.9, 'Planilha'),
  ('Coturno', '46', 'Par', 0, 8, 58.9, 'Planilha'),
  ('Coturno', '47', 'Par', 0, 5, 58.9, 'Planilha'),
  ('Coturno', '48', 'Par', 0, 3, 58.9, 'Planilha'),
  ('Coturno', '50', 'Par', 0, 2, 58.9, 'Planilha'),
  ('Detector de Metal (Lua Tec - LWJ58)', 'Único', 'Cada', 1, 2, 34.9, 'Planilha'),
  ('Empunhadura Révolver Taurus', 'Único', 'Cada', 2, 1, 84.43, 'Planilha'),
  ('Fiel amarela', 'Único', 'Cada', 0, 50, 11.11, 'Planilha'),
  ('Filtro para respirador', 'Único', 'Cada', 12, 6, 18.5, 'Planilha'),
  ('Galão Água - 5L (Termolar)', 'Único', 'Cada', 0, 0, 22.35, 'Planilha'),
  ('Giroflex Copo', 'Único', 'Cada', 8, 0, 72.0, 'Planilha'),
  ('Giroflex Parabrisa', 'Único', 'Cada', 0, 0, 109.0, 'Planilha'),
  ('Gravata Azul - Lisa', 'Único', 'Cada', 0, 5, 25.0, 'Planilha'),
  ('Gravata Preta - Lisa', 'Único', 'Cada', 3, 5, 25.42, 'Planilha'),
  ('Guarda Chuva', 'Único', 'Cada', 0, 2, 113.9, 'Planilha'),
  ('Jaqueta Corta-Vento - Preta', 'G', 'Cada', 5, 0, 65.0, 'Planilha'),
  ('Kit Proteção Moto - c/ joelheira e cotoveleira', 'Único', 'Cada', 1, 10, null, 'Planilha'),
  ('Lanterna Tática', 'Único', 'Cada', 4, 10, 30.53, 'Planilha'),
  ('Livro de Ocorrência (100 folhas - 200mm x 298mm)', 'Único', 'Cada', 50, 30, 11.3, 'Planilha'),
  ('Luva Anticorte', 'EG', 'Par', 0, 5, null, 'Planilha'),
  ('Luva de Vaqueta', 'Único', 'Par', 16, 15, 11.5, 'Planilha'),
  ('Luva Grip - Azul ou Preta', 'G', 'Par', 0, 15, 11.9, 'Planilha'),
  ('Luva Látex - Amarela', 'M', 'Par', 0, 25, 4.5, 'Planilha'),
  ('Luva Látex - Amarela', 'G', 'Par', 0, 25, 4.5, 'Planilha'),
  ('Luva Látex - Azul', 'G', 'Par', 0, 10, 10.56, 'Planilha'),
  ('Luva Látex - Azul', 'EG', 'Par', 0, 10, 10.56, 'Planilha'),
  ('Luva Látex - Azul', 'M', 'Par', 0, 10, 10.56, 'Planilha'),
  ('Luva Latex - Laranja', 'M', 'Par', 2, 0, 8.5, 'Planilha'),
  ('Luva Látex Ranhurada Volk', 'G', 'Par', 3, 20, 10.98, 'Planilha'),
  ('Luva Meio Dedo de Couro - Moto', 'GG', 'Par', 1, 1, 45.0, 'Planilha'),
  ('Luva Pigmentada Preta', 'Único', 'Par', 0, 20, 2.5, 'Planilha'),
  ('Luva PVC (Smart 36) - Verde', 'Único', 'Par', 13, 10, 21.45, 'Planilha'),
  ('Marmi Quent', 'Único', 'Cada', 0, 0, 125.0, 'Planilha'),
  ('Máscara de Proteção PFF2 S', 'Único', 'Cada', 0, 50, 0.9, 'Planilha'),
  ('Máscaras de Pano', 'Único', 'Par', 0, 0, 3.9, 'Planilha'),
  ('Óculos de Segurança Incolor', 'Único', 'Cada', 1, 15, 2.77, 'Planilha'),
  ('Óculos de Segurança Preto', 'Único', 'Cada', 0, 10, 2.77, 'Planilha'),
  ('Oleo 2T Castrol 500ml P/ Roçadeira', 'Único', 'Cada', 0, 5, 25.01, 'Planilha'),
  ('Ombrelone Reformado 2,00mt', 'Único', 'Cada', 3, 0, 390.0, 'Planilha'),
  ('Ombrelone Reformado 2,40mt', 'Único', 'Cada', 0, 0, 420.0, 'Planilha'),
  ('Paletó Masculino - Max Forte', null, 'Cada', 6, 0, 240.0, 'Planilha'),
  ('Paletó Masculino - Serviços', null, 'Cada', 2, 0, 240.0, 'Planilha'),
  ('Perneira (Couro)', 'Único', 'Par', 3, 2, 34.0, 'Planilha'),
  ('Perneira (Preta)', 'Único', 'Par', 0, 2, 40.0, 'Planilha'),
  ('Porta Tonfa', null, 'Cada', 9, 0, 26.0, 'Planilha'),
  ('Protetor Auricular', 'Único', 'Cada', 211, 50, 0.8, 'Planilha'),
  ('Protetor Facial Articulado', 'Único', 'Cada', 4, 2, 26.0, 'Planilha'),
  ('Protetor Solar 120ml FPS 30 (Nutriex)', 'Único', 'Cada', 5, 0, 15.0, 'Planilha'),
  ('Protetor Solar FPS 30 4L', null, 'Cada', 0, 0, 289.47, 'Planilha'),
  ('Respirador 1\4 - semi facial com filtro', 'Único', 'Cada', 2, 0, 24.74, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '34', 'Par', 5, 1, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '35', 'Par', 7, 1, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '36', 'Par', 14, 3, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '37', 'Par', 11, 2, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '38', 'Par', 12, 5, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '39', 'Par', 24, 3, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '40', 'Par', 19, 5, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '41', 'Par', 24, 3, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '42', 'Par', 7, 5, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '43', 'Par', 12, 3, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '44', 'Par', 4, 2, 58.4, 'Planilha'),
  ('Sapato ASG Antiderrapante Unisex', '45', 'Par', 2, 1, 58.4, 'Planilha'),
  ('Sapato Social Feminino', '34', 'Par', 4, 2, 49.95, 'Planilha'),
  ('Sapato Social Feminino', '35', 'Par', 4, 3, 49.95, 'Planilha'),
  ('Sapato Social Feminino', '36', 'Par', 5, 5, 49.95, 'Planilha'),
  ('Sapato Social Feminino', '37', 'Par', 8, 8, 49.95, 'Planilha'),
  ('Sapato Social Feminino', '38', 'Par', 1, 8, 49.95, 'Planilha'),
  ('Sapato Social Feminino', '39', 'Par', 1, 8, 49.95, 'Planilha'),
  ('Sapato Social Feminino', '40', 'Par', 1, 3, 49.95, 'Planilha'),
  ('Sapato Social Feminino', '41', 'Par', 1, 2, 49.95, 'Planilha'),
  ('Sapato Social Feminino', '42', 'Par', 3, 1, 49.95, 'Planilha'),
  ('Sapato Social Feminino', '43', 'Par', 3, 1, 49.95, 'Planilha'),
  ('Sapato Social Masculino', '38', 'Par', 1, 1, 59.76, 'Planilha'),
  ('Sapato Social Masculino', '39', 'Par', 2, 1, 59.76, 'Planilha'),
  ('Sapato Social Masculino', '40', 'Par', 4, 5, 59.76, 'Planilha'),
  ('Sapato Social Masculino', '41', 'Par', 2, 4, 59.76, 'Planilha'),
  ('Sapato Social Masculino', '42', 'Par', 0, 8, 59.76, 'Planilha'),
  ('Sapato Social Masculino', '43', 'Par', 1, 8, 59.76, 'Planilha'),
  ('Sapato Social Masculino', '44', 'Par', 1, 8, 59.76, 'Planilha'),
  ('Sapato Social Masculino', '45', 'Par', 0, 4, 59.76, 'Planilha'),
  ('Sapato Social Masculino', '46', 'Par', 2, 2, 59.76, 'Planilha'),
  ('Sapato Social Masculino', '47', 'Par', 1, 1, 59.76, 'Planilha'),
  ('Smatphone Galaxy A07', 'Único', 'Cada', 0, 2, 745.0, 'Planilha'),
  ('Spray de Defesa Pessoal', 'Único', 'Cada', 1, 1, 135.09, 'Planilha'),
  ('Suporte p/ botton', 'Único', 'Cada', 32, 15, null, 'Planilha'),
  ('Tonfa fixa', 'Único', 'Cada', 9, 5, 35.0, 'Planilha'),
  ('Totem', 'Único', 'Cada', 2, 5, 650.0, 'Planilha'),
  ('Touca ASG', 'Único', 'Cada', 8, 5, 33.0, 'Planilha')
on conflict (name_key, size_key) do nothing;
