import type { FormField } from './types';

export const DEFAULT_FIELDS: FormField[] = [
  {
    id: 'email',
    system: 'email',
    type: 'email',
    label: 'Seu e-mail executivo',
    help: 'Só e-mails cadastrados pelo almoxarifado podem enviar solicitações.',
    placeholder: 'nome@empresa.com.br',
    required: true,
  },
  {
    id: 'colaborador',
    system: 'colaborador',
    type: 'text',
    label: 'Colaborador',
    help: 'Nome de quem vai receber o item, não o seu.',
    placeholder: 'Nome completo do colaborador',
    required: true,
  },
  {
    id: 'posto',
    system: 'posto',
    type: 'select',
    label: 'Posto',
    options: ['Posto 01', 'Posto 02', 'Posto 03'],
    required: true,
  },
  {
    id: 'motivo',
    type: 'textarea',
    label: 'Motivo da solicitação',
    placeholder: 'Ex.: bota rasgou durante o turno, colaborador novo, troca de tamanho…',
    required: true,
  },
  {
    id: 'categoria',
    type: 'checkbox',
    label: 'O que está sendo pedido',
    options: ['Fardamento', 'Calçado', 'EPI'],
    required: true,
  },
  {
    id: 'itens',
    type: 'checkbox',
    label: 'Itens',
    options: [
      'Camisa',
      'Calça',
      'Jaqueta',
      'Boné',
      'Bota de segurança',
      'Sapato',
      'Luva',
      'Capacete',
      'Óculos de proteção',
      'Protetor auricular',
      'Máscara',
      'Colete refletivo',
    ],
    required: true,
  },
  {
    id: 'tamanho_roupa',
    type: 'select',
    label: 'Tamanho do fardamento',
    options: ['PP', 'P', 'M', 'G', 'GG', 'XG', 'Não se aplica'],
    required: true,
  },
  {
    id: 'tamanho_calcado',
    type: 'select',
    label: 'Número do calçado',
    options: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', 'Não se aplica'],
    required: true,
  },
  {
    id: 'quantidade',
    type: 'number',
    label: 'Quantidade',
    placeholder: '1',
    required: true,
  },
  {
    id: 'anexos',
    system: 'anexos',
    type: 'file',
    label: 'Fotos e vídeos',
    help: 'Opcional. Use em caso de ocorrência (item danificado, acidente etc.).',
    required: false,
  },
];
